CFG_TEE_TA_LOG_LEVEL ?= 4
CPPFLAGS += -DCFG_TEE_TA_LOG_LEVEL=$(CFG_TEE_TA_LOG_LEVEL)

# The UUID for the Trusted Application
BINARY=ebb6f4b5-7e33-4ad2-9802-e64f2a7cc20c

include $(TA_DEV_KIT_DIR)/mk/ta_dev_kit.mk
