/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class HelloJni */

#ifndef _Included_HelloJni
#define _Included_HelloJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     HelloJni
 * Method:    sayHello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_HelloJni_sayHello
  (JNIEnv *, jclass);

/*
 * Class:     HelloJni
 * Method:    setInt
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_HelloJni_setInt
  (JNIEnv *, jobject, jint);

/*
 * Class:     HelloJni
 * Method:    getInt
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_HelloJni_getInt
  (JNIEnv *, jobject);

/*
 * Class:     HelloJni
 * Method:    setUser
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_HelloJni_setUser
  (JNIEnv *, jobject, jstring);

/*
 * Class:     HelloJni
 * Method:    getUser
 * Signature: ()LUser;
 */
JNIEXPORT jobject JNICALL Java_HelloJni_getUser
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
