CFG_TEE_TA_LOG_LEVEL ?= 4
CPPFLAGS += -DCFG_TEE_TA_LOG_LEVEL=$(CFG_TEE_TA_LOG_LEVEL)

# The UUID for the Trusted Application
BINARY=59e4d3d3-0199-4f74-b94d-53d3daa57d73

include $(TA_DEV_KIT_DIR)/mk/ta_dev_kit.mk
